import 'dart:async';

import 'package:cek_film_app/controllers/controllers.dart';
import 'package:cek_film_app/models/models.dart';
import 'package:cek_film_app/shared/shared.dart';
import 'package:cek_film_app/ui/widgets/widgets.dart';
import 'package:cek_film_app/utils/root.dart';
import 'package:curved_navigation_bar/curved_navigation_bar.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:random_color/random_color.dart';
import 'package:get_storage/get_storage.dart';
import 'package:intl_phone_number_input/intl_phone_number_input.dart';
import 'package:lottie/lottie.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:numeric_keyboard/numeric_keyboard.dart';
import 'package:material_floating_search_bar/material_floating_search_bar.dart';
// import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:pin_code_fields/pin_code_fields.dart';
// import 'package:otp/otp.dart';
import 'package:sms_autofill/sms_autofill.dart';
import 'package:shimmer/shimmer.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter_signin_button/flutter_signin_button.dart';
part 'splashscreen_page.dart';
part 'on_boarding_page.dart';
part 'main_page.dart';
part 'login_page.dart';
part 'sign_up_page.dart';
part 'registration_data.dart';
part 'preference_page.dart';
part 'home_page.dart';
part 'my_review_page.dart';
part 'verify_otp_page.dart';
part 'detail_movie_page.dart';
